PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org2: See "Org2" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.biz2.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
