# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.settle.com:
  ca.org1.biz1.com:
  peer0.org1.biz1.com:
  peer1.org1.biz1.com:

networks:
  sbn:

services:
  ca.org1.biz1.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.biz1.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.biz1.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.biz1.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.biz1.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.biz1.com
    networks:
      - sbn

  orderer.settle.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.settle.com
    container_name: orderer.settle.com
    networks:
      - sbn

  peer0.org1.biz1.com:
    container_name: peer0.org1.biz1.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.biz1.com
    networks:
      - sbn

  peer1.org1.biz1.com:
    container_name: peer1.org1.biz1.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.biz1.com
    networks:
      - sbn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.biz1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.biz1.com/peers/peer0.org1.biz1.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.biz1.com/peers/peer0.org1.biz1.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.biz1.com/peers/peer0.org1.biz1.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.biz1.com/users/Admin@org1.biz1.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        # - ./channel-artifacts/Org1OrdererGenesis:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.org1.biz1.com
      - orderer.settle.com
      - peer0.org1.biz1.com
      - peer1.org1.biz1.com
    networks:
      - sbn